# Generated by Django 6.0.5 on 2026-05-13 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.region'),
        ),
    ]
